name: Makefile CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make build

    - name: Run check
      run: make test

    - name: Audit code
      run: make audit

    - name: Run distcheck
      run: make distcheck
